### PR TITLE
Created the events page showing static events with animation using css

### PR DESCRIPTION
**Pull request by Jigneshpawar**

### CODE REVIEW

**Comment by vipul-rajput** [comment]
We have to make page of already happened event with some glimpse and short discrimination with guest. Add more details.

**Comment by Jigneshpawar** [comment]
Okay....

**Comment by Jigneshpawar** [comment]
Updated the events section..
Added previous events wherin The details of the event are been displayed on hovering over Read More text

**Comment by vipul-rajput** [comment]
Great Work. If you want to contribute more, join us :[Discord server]( https://discord.gg/yxPakE). 
Thank you...

**Comment by Jigneshpawar** [comment]
Hey, can you add hacktoberfest-accepted label to my pull req...
Hactoberfest have changed their rules
https://hacktoberfest.digitalocean.com/hacktoberfest-update?utm_medium=email&utm_source=hacktoberfest&utm_campaign=main_&utm_content=response

**Comment by Jigneshpawar** [comment]
add here please...
Coz rules say to add here..

Sorry for inconvinience....

**Comment by vipul-rajput** [comment]
done...

**Pull request merged**
